name: sync-images

on:
  push:
    branches:
      - sync
  schedule:
    - cron: "0 * * * *"

jobs:
  sync-images:
    runs-on: ubuntu-20.04
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Sync images
        shell: bash
        env:
          REGISTRY_DOMAIN: ${{ secrets.REGISTRY_DOMAIN }}
          REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
        run: |
          sudo skopeo login ${REGISTRY_DOMAIN}  -u ${REGISTRY_USER} -p ${REGISTRY_PASSWORD}
          sudo bash sync-images.sh ${REGISTRY_DOMAIN}
